creation_rules:
  - path_regex: .*\.sops\.ya?ml
    encrypted_regex: '^(data|stringData)$'
    key_groups:
      - age:
          - age1cn8jcfpmkyr2f6q3xxe5k8uwvk0apk0ma9psv3kxdvr8fuh45e6smry3ks
  - path_regex: .*
    key_groups:
      - age:
          - age1cn8jcfpmkyr2f6q3xxe5k8uwvk0apk0ma9psv3kxdvr8fuh45e6smry3ks
stores:
  yaml:
    indent: 2
