---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-controller
  namespace: flux-system
spec:
  interval: 5m
  path: "./metallb/controller"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: metallb
      namespace: metallb-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-config
  namespace: flux-system
spec:
  dependsOn:
    - name: metallb-controller
  interval: 5m
  path: "./metallb/config"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
