apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: ${namespace}
spec:
  acme:
    email: ${email}
    server: ${server}
    privateKeySecretRef:
      name: letsencrypt-private-key
    solvers:
      - dns01:
          route53:
            region: ${aws_region}
            accessKeyIDSecretRef:
              name: ${secret_name}
              key: access-key-id
            secretAccessKeySecretRef:
              name: ${secret_name}
              key: secret-access-key
