apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik.${domain}
  namespace: ${namespace}
spec:
  dnsNames:
    - "*.${domain}"
  secretName: traefik.${domain}
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
