apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "America/New_York"
  CILIUM_ADDRESS_CIDR: "10.100.6.128/26"
  LETS_ENCRYPT_SERVER: "https://acme-v02.api.letsencrypt.org/directory"
