machine:
  install:
    disk: ${install_disk}
  network:
    hostname: ${hostname}
    interfaces:
      - interface: ${interface}
        addresses:
          - ${ip}/${netmask}
        routes:
          - network: 0.0.0.0/0
            gateway: ${gateway}
%{ if vip != "" ~}
        vip:
          ip: ${vip}
%{ endif ~}
    nameservers:
%{ for ns in nameservers ~}
      - ${ns}
%{ endfor ~}

cluster:
  allowSchedulingOnControlPlanes: false
  network:
    podSubnets:
      - 192.168.0.0/16
    serviceSubnets:
      - 172.16.0.0/12
