cert-manager:
  acme:
    email: ENC[AES256_GCM,data:y7jYOE0cBoEASzacTd1OdUDaDw==,iv:6sEPcj0CeUj8MJ1joDUZvY3ntMnQK+dPaqqsr1HY/U0=,tag:xnkrPgIprENl/e37F86tig==,type:str]
    server: ENC[AES256_GCM,data:u2tbVHsPBojdiInvNztbcWnQ0xE2Ha0nwc0tqhWobjoafUBx7bqOhntL778HlQ==,iv:FOxdG2Sr8SCxSWzYNLZxp+h0/uv6tnKA5AO/j10YzIY=,tag:JUnlRGEqlpGlN1KKgriRPw==,type:str]
  aws:
    region: ENC[AES256_GCM,data:7ZKJqLMmEE8G,iv:9puzi0vYF6cJ6NGaNP+Zg2kVRfPZWa4Ue0HRMqbDJSM=,tag:4aTHFvWu5yfD6cmClHJEwg==,type:str]
    key_id: ENC[AES256_GCM,data:1xF9aVymED7KB8vgUM9LT5EWxrY=,iv:i59NAMZ2vEp2JOLKg0SbJLinH75A5BjYXJWowrwqXj4=,tag:ugW4vis2SsDzRTN1DLGIog==,type:str]
    secret: ENC[AES256_GCM,data:T2oRRiwtJfgvNRMGyfDcNib9Y9wTJJJ71AP1EW2GVNE5dC0Lu2AqPA==,iv:bABDc47dm3Kw+pxKhVcExcSuw2YXVTFXeUPoQkj/lT0=,tag:CxBp0AJnWVELSRx1BsPjGA==,type:str]
sops:
  age:
    - recipient: age1cn8jcfpmkyr2f6q3xxe5k8uwvk0apk0ma9psv3kxdvr8fuh45e6smry3ks
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvbUJ1VTBHaCtMSENRRGpz
        a1BrRTFKS1owVUt6WWpNQTY3eDhuWE9jSlY4CjYrYXUwazI5SjE5ZzdXRnpvVENP
        WjhmUGtUQnpOdFhYOGtYWnBCTVZxeW8KLS0tIFd2bzArY0JTcS9WbmEyL3JsTGF1
        VnVGeW9vZEpmWVRRaWtySDJjMVFCa2MKfcwSL8ZJiZxXYMYMOX6Mn95aYgY5Dh1H
        wrdiqJ76SFjcU9GFHGCIAquMgiz9H/cT5voEhXzYLTFs0tzThakIVA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-29T00:01:27Z"
  mac: ENC[AES256_GCM,data:Kg4rGOdpURFlZl99lIDnH7qjXMSFWT2yl77yYHHOVWff2DsKF+W8jAMA2Koa/PPSltX2z8rpjQQC7N8DKhC7WL062B8pl5thHiUwR6RsKCXMVG7Xis6Nka9ZK2mP2sUuKkQ7FVMRfUkrvFkn7agG3peyUqKoJjxEsFlDUmPicn4=,iv:AD93/NgEywNrsDs1ZCit6rorljSqqRzzRMIjVzYMRlA=,tag:bA+u9fBQGkqJafEeGHHtRA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.10.2
