letsencrypt:
  email: ENC[AES256_GCM,data:ur2oqw+zLgvktyd6b8RqiPeaNg==,iv:Y09DZqqGt2gEgK2tGKurkU8NlOiDQ8ll1kmJjNAQltQ=,tag:BNPUHP7NqGKMJme38zNo3A==,type:str]
sops:
  age:
    - recipient: age1cn8jcfpmkyr2f6q3xxe5k8uwvk0apk0ma9psv3kxdvr8fuh45e6smry3ks
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSQUlJeFdRM05peTBISG1y
        bHpNdG05RkY4TTY1bWhnckhYcVU3YWh1TXdNCm5yNEdCZnBMWVBDL2p5Y1huZWhG
        dHY1T05oUUVzTUNvL3ZxRHZwTXRUZW8KLS0tIEFMK3pteFhHUVEyejRhcXF3OW54
        eEY1MmtDbEMwZ08rQlVsTjhzVkozc0EKc4zh1OKJP5K+yzplaHhFpy1z+DHCfxgX
        6pX19Uin6+ZWIBMzJzgbnczWRbKI2Lp13nZVb3ink/BuFxNpTaFLdw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-28T21:07:56Z"
  mac: ENC[AES256_GCM,data:crq5mnBfGv11pC9Stywp7jq2Pi8q59axZzz+xQOn+4GH/dHMCTgqqsq5u9FdN17VJUYH9EJKTd08BNZzV1t1cD1rF7ZpNrq97Bg5F6jql1kf5UCKSKGXHdlU/ZwPGXa1q2U2KX60ynuJt2jD6Y00rP6QZV1phSd3mhjmvEL44Vo=,iv:n8ABRAwi3EpJIT13muofpAFSww9qF/u+hMJEXrKKRxo=,tag:bokLbXmX17JlKi6Dbt7Kxw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.10.2
