# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: cloudflare-api-key-secret
#   namespace: cert-manager
# type: Opaque
# stringData:
#   api-key: "${SECRET_CLOUDFLARE_API_KEY}"
# ---
# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: certificate
#   namespace: cert-manager
# spec:
#   secretName: "${SECRET_DOMAIN}"
#   subject:
#     organizations:
#       - cert-manager
#   dnsNames:
#     - "${SECRET_DOMAIN}"
#     - "*.${SECRET_DOMAIN}"
#   issuerRef:
#     name: letsencrypt
#     kind: ClusterIssuer
