---
# https://docs.cilium.io/en/latest/network/l2-announcements
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: l2-announcement-policy
spec:
  externalIPs: true
  loadBalancerIPs: true
  # NOTE: interfaces might need to be set if you have more than one active NIC on your hosts
  # interfaces:
  #   - ^eno[0-9]+
  #   - ^eth[0-9]+
---
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: ip-pool
spec:
  allowFirstLastIPs: "Yes"
  blocks:
    - cidr: "${CILIUM_ADDRESS_CIDR}"
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: cilium
spec:
  controllerName: io.cilium/gateway-controller
---
apiVersion: v1
kind: Namespace
metadata:
  name: gateway
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: cilium-gateway
  namespace: gateway
  # annotations:
  #   cert-manager.io/issuer: letsencrypt
spec:
  gatewayClassName: cilium
  addresses:
    - type: IPAddress
      value: 10.100.6.130
  listeners:
    - protocol: HTTPS
      port: 443
      name: https-gateway
      hostname: "*.${SECRET_DOMAIN}"
      tls:
        certificateRefs:
          - kind: Secret
            name: letsencrypt-cloudflare
            namespace: cert-manager
      allowedRoutes:
        namespaces:
          from: All
    - protocol: HTTPS
      port: 443
      name: https-domain-gateway
      hostname: "${SECRET_DOMAIN}"
      tls:
        certificateRefs:
          - kind: Secret
            name: letsencrypt-cloudflare
            namespace: cert-manager
      allowedRoutes:
        namespaces:
          from: All
