---
apiVersion: v1
kind: Namespace
metadata:
  name: gateway
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token
  namespace: gateway
type: Opaque
stringData:
  api-token: "${SECRET_CLOUDFLARE_TOKEN}"
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-issuer
  namespace: gateway
spec:
  acme:
    email: "${SECRET_LETS_ENCRYPT_EMAIL}"
    server: "${LETS_ENCRYPT_SERVER}"
    privateKeySecretRef:
      name: letsencrypt-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-token
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: cilium-gateway
  namespace: gateway
  annotations:
    cert-manager.io/issuer: letsencrypt-issuer
spec:
  gatewayClassName: cilium
  addresses:
    - type: IPAddress
      value: 10.100.6.130
  listeners:
    - protocol: HTTPS
      port: 443
      name: https-gateway
      hostname: "*.${SECRET_DOMAIN}"
      tls:
        certificateRefs:
          - kind: Secret
            name: letsencrypt-wildcard-cert
      allowedRoutes:
        namespaces:
          from: All
    - protocol: HTTPS
      port: 443
      name: https-domain-gateway
      hostname: "${SECRET_DOMAIN}"
      tls:
        certificateRefs:
          - kind: Secret
            name: letsencrypt-domain-cert
      allowedRoutes:
        namespaces:
          from: All
