# Put a pod on every node in the cluster so it is always available
deployment:
  kind: DaemonSet
ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`traefik.${domain}`)
    entryPoints:
      - websecure
logs:
  access:
    enabled: true
api:
  dashboard: true
  insecure: true
providers:
  kubernetesGateway:
    enabled: true
gateway:
  namespacePolicy: All
ports:
  web:
    redirections:
      entryPoint:
        to: websecure
        scheme: https
        permanent: true
  websecure:
    tls:
      enabled: true
# securityContext:
#   seccompProfile:
#     type: RuntimeDefault
