machine:
  install:
    disk: ${install_disk}
    image: ${installer_url}
  network:
    hostname: ${hostname}
    interfaces:
      - interface: ${interface}
        addresses:
          - ${ip}/${netmask}
        routes:
          - network: 0.0.0.0/0
            gateway: ${gateway}
