apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami-deployment
  namespace: default
  labels:
    app: whoami
spec:
  replicas: 2
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
      - name: whoami
        image: traefik/whoami:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: whoami-loadbalancer
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: whoami
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: whoami-gateway
  namespace: default
spec:
  gatewayClassName: cilium
  listeners:
    - name: https-listener
      protocol: HTTPS
      port: 443
      hostname: whoami.baconvacation.com
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: letsencrypt-cloudflare
            namespace: cert-manager
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: whoami-https-route
  namespace: default
spec:
  parentRefs:
    - name: whoami-gateway
  hostnames:
    - whoami.baconvacation.com
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: whoami
          port: 80
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: whoami-ingress
#   namespace: default
# spec:
#   ingressClassName: cilium
#   rules:
#     - host: whoami.baconvacation.com
#       http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: whoami
#                 port:
#                   number: 80
#   tls:
#     - hosts:
#         - whoami.baconvacation.com
#       secretName: letsencrypt-cloudflare
